# The Usage of The "SimplesMM" Class
---
**The class' inputs and their types**

         data:             coefficient of the variable                 ==> numpy.ndarray
         sts:              the result of every equation                ==> numpy.ndarray
         z:                coefficient of the z equation               ==> list 
         situations:       the situation of every equation(=,<=,>=)    ==> list
         columns:          the names of the variables                  ==> list 
         M = 1000                                                      ==> 
         isMax==True :     the situation of z(max or min)              ==> boolean
         iteration=100 :   max iteration value                         ==>

In [1]:
#importing the class
from simpleksM import SimpleksMM
import numpy as np

## Example: $Z_{max}$
---
$$
    Z_{max} : 2X_{1} + 4X_{2} + 6X_{3} + 6X_{4}
$$

$$
    4X_{1} + 4X_{2} + 6X_{3} + 2X_{4} = 100
$$

$$
    2X_{1} + 2X_{2} + 4X_{3} + 2X_{4} \le 80
$$

$$
    2X_{1} + 2X_{2} + 2X_{3} + 4X_{4} \ge 60
$$

$$
    X_{1} , X_{2} , X_{3} , X_{4} \ge 0
$$

In [2]:
#creating the inputs
data = np.array([
    [4,4,6,2],
    [2,2,4,2],
    [2,2,2,4]
])
sts = np.array([100,80,60])
z = [2,4,6,6]
situations = ["=" , "<=" , ">="]
columns = ["x1","x2","x3","x4"]

In [3]:
#creating the object
mMethode = SimpleksMM(data=data , sts=sts , z=z , situations=situations , columns=columns , isMax=True)

In [4]:
#with the method, the question is solved
mMethode.solve()

In [5]:
#with the method, the answers are assigned to a variable
answers = mMethode.show()

In [6]:
for i in answers.keys():
    print(i)
    print(answers[i])
    print("-"*10)

data
[[ 1.   1.   1.   0.   0.5 -0.5  0.   0. ]
 [ 0.   0.   4.   0.  -1.   3.   1.  -1. ]
 [ 0.   0.   1.   1.  -0.5  1.   0.   0. ]]
----------
z
[2, 4, 6, 6, -1000, 0, 0, -1000]
----------
columns
['x1', 'x2', 'x3', 'x4', 'A1', 'S2', 'S3', 'A3']
----------
cj
[[4.]
 [0.]
 [6.]]
----------
cj_name
['x2', 'S3', 'x4']
----------
answer
220.0
----------
sts
[[10.]
 [80.]
 [30.]]
----------


In [7]:
#answer of the question(Zmax)
answers["answer"]

220.0

In [8]:
#values of the variables
for i in range(len(answers["sts"])):
    print(answers["cj_name"][i] , "=" , answers["sts"][i])

x2 = [10.]
S3 = [80.]
x4 = [30.]


In [9]:
#last status of the data
answers["data"]

array([[ 1. ,  1. ,  1. ,  0. ,  0.5, -0.5,  0. ,  0. ],
       [ 0. ,  0. ,  4. ,  0. , -1. ,  3. ,  1. , -1. ],
       [ 0. ,  0. ,  1. ,  1. , -0.5,  1. ,  0. ,  0. ]])

In [10]:
#last status table
mMethode.table()

cj   x1   x2   x3   x4   A1   S2   S3   A3   STS
x2  4.0  1.0  1.0  1.0  0.0  0.5 -0.5  0.0  0.0  10.0
S3  0.0  0.0  0.0  4.0  0.0 -1.0  3.0  1.0 -1.0  80.0
x4  6.0  0.0  0.0  1.0  1.0 -0.5  1.0  0.0  0.0  30.0

## Example: $Z_{min}$
---
$$
    Z_{min} : 3X_{1} + 2X_{2} + X_{3}
$$

$$
    X_{1} + X_{2} + X_{3} \ge 4
$$

$$
    X_{2} - X_{3} \le 2
$$

$$
    X_{1} + X_{2} + 2X_{3} = 6
$$

$$
    X_{1} , X_{2} , X_{3} \ge 0
$$

In [11]:
#creating the inputs
data = np.array([
    [1,1,1],
    [0,1,-1],
    [1,1,2]
])
sts = np.array([4,2,6])
z = [3,2,1]
situations = [">=" , "<=" , "="]
columns = ["x1","x2","x3"]

In [12]:
mMethode2 = SimpleksMM(data,sts,z,situations,columns,isMax=False)
mMethode2.solve()
answers_2 = mMethode2.show()

In [13]:
for i in answers_2.keys():
    print(i)
    print(answers_2[i])
    print("-"*10)

data
[[ 1.  1.  0. -2.  2.  0. -1.]
 [-1.  0.  0.  3. -3.  1.  2.]
 [ 0.  0.  1.  1. -1.  0.  1.]]
----------
z
[3, 2, 1, 0, 1000, 0, 1000]
----------
columns
['x1', 'x2', 'x3', 'S1', 'A1', 'S2', 'A3']
----------
cj
[[2.]
 [0.]
 [1.]]
----------
cj_name
['x2', 'S2', 'x3']
----------
answer
6.0
----------
sts
[[2.]
 [2.]
 [2.]]
----------


In [14]:
#Zmin
answers_2["answer"]

6.0

In [15]:
#values of the variables
for i in range(len(answers_2["sts"])):
    print(answers_2["cj_name"][i] , "=" , answers_2["sts"][i])

x2 = [2.]
S2 = [2.]
x3 = [2.]


In [16]:
#last status of the data
answers["data"]

array([[ 1. ,  1. ,  1. ,  0. ,  0.5, -0.5,  0. ,  0. ],
       [ 0. ,  0. ,  4. ,  0. , -1. ,  3. ,  1. , -1. ],
       [ 0. ,  0. ,  1. ,  1. , -0.5,  1. ,  0. ,  0. ]])

In [17]:
#last status table
mMethode2.table()

cj   x1   x2   x3   S1   A1   S2   A3  STS
x2  2.0  1.0  1.0  0.0 -2.0  2.0  0.0 -1.0  2.0
S2  0.0 -1.0  0.0  0.0  3.0 -3.0  1.0  2.0  2.0
x3  1.0  0.0  0.0  1.0  1.0 -1.0  0.0  1.0  2.0